
name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]
    runs-on: ubuntu-latest

    env:
      Solution_Name: SqlQueryBuilder.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Display dotnet version
      run: dotnet --version
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Execute unit tests
      run: dotnet test

